// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'; // For kIsWeb


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD030yl_YrR0zD21gW6IxhN2agURanQ6NM',
    appId: '1:180381279721:web:9c815ec7e3359731079778',
    messagingSenderId: '180381279721',
    projectId: 'our-app-47f53',
    authDomain: 'our-app-47f53.firebaseapp.com',
    storageBucket: 'our-app-47f53.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCopedNGoZezkes_7STPtvJK3Sq24GaLoU',
    appId: '1:180381279721:android:15b08cdeb8cba8b2079778',
    messagingSenderId: '180381279721',
    projectId: 'our-app-47f53',
    storageBucket: 'our-app-47f53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp5bNlPuit9H3Ys0qv2FGHZZagO6uhgKM',
    appId: '1:180381279721:ios:902e294c7c006045079778',
    messagingSenderId: '180381279721',
    projectId: 'our-app-47f53',
    storageBucket: 'our-app-47f53.appspot.com',
    iosBundleId: 'com.example.ourApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp5bNlPuit9H3Ys0qv2FGHZZagO6uhgKM',
    appId: '1:180381279721:ios:902e294c7c006045079778',
    messagingSenderId: '180381279721',
    projectId: 'our-app-47f53',
    storageBucket: 'our-app-47f53.appspot.com',
    iosBundleId: 'com.example.ourApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD030yl_YrR0zD21gW6IxhN2agURanQ6NM',
    appId: '1:180381279721:web:9cbe4844aac0fd4b079778',
    messagingSenderId: '180381279721',
    projectId: 'our-app-47f53',
    authDomain: 'our-app-47f53.firebaseapp.com',
    storageBucket: 'our-app-47f53.appspot.com',
  );
}
